name: privacy-policy-evaluator
channels:
  - defaults
dependencies:
  - numpy
  - pandas
  - pip
  - nltk
  - matplotlib
#  - pip:                            # Packages installed from PyPI
#    - requests==2.21.0
